### ISSUE TITLE
parsePromise.always is not a function

### ISSUE THREAD

**Issue by basharov** [mcwebb/angular-parse-patch#3]
I found a bug: Angular now names `finally` what was `always` method before. I tried to replace `always` call here https://github.com/mcwebb/angular-parse-patch/blob/master/src/angular-parse-patch.js#L114 to `finally` and it fixed the issue.

**Comment by mcwebb** [comment]
Thanks @basharov, I've actually just run in to the same bug.
I'll merge your PR, since it fixed the issue for me too, however it actually shouldn't have worked since that parsePromise is meant to be an instance of Parse.Promise rather than $q. So this stinks of a wider issue. Probably related to #1
